### PR TITLE
Add shutdown hook for stopping system

### PR DESCRIPTION
**Pull request by eunmin**
This patch add shutdown hook for stopping system of the component when the jvm is terminated or the program exits normally.

### CODE REVIEW

**Comment by weavejester** [comment]
Sorry for the delayed response. I think this is a good idea, but I think the namespace should be changed from `duct.utils` to `duct.util.runtime`, and instead of returning the `Thread` object, instead allow shutdown hooks to be specified by a user-defined key, similar to `add-watch`.

So for instance, we'd use it something like:

```clojure
(add-shutdown-hook ::stop-system #(component/stop system))
```

Naturally we'd also have:

```clojure
(remove-shutdown-hook ::stop-system)
```

And adding a shutdown hook to the same key would overwrite it.

**Comment by eunmin** [comment]
Thanks a lot for the detailed feedback. I have amended the commit incorporating your suggestions.

**Comment by weavejester** [comment]
Thanks for the updates! The only remaining issue is that the new functions are not thread safe, and adding a new shutdown hook with the same key doesn't remove the old one.

We could use `locking`, but perhaps instead we could do something like:

```clojure
(def ^:private hooks (atom {}))

(defn- run-hooks []
  (doseq [f (vals @hooks)] (f)))

(defonce ^:private init-shutdown-hook
  (delay (.addShutdownHook (Runtime/getRuntime) (Thread. #'run-hooks))))

(defn add-shutdown-hook [k f]
  (force init-shutdown-hook)
  (swap! hooks assoc k f))

(defn remove-shutdown-hook [k]
  (swap! hooks dissoc k))
```

In other words, we only ever set up one "real" shutdown hook, which just runs a function that iterates through all our user hooks.

We use `defonce` and `delay` to ensure the shutdown hook is set only once, and we pass `run-hooks` as a var just in case we need to pick up possible changes made to the namespace.

**Comment by eunmin** [comment]
Thank you for reply.
Which functions are not thread-safe?

java.lang.Runtime/addShutdownHook method is thread-safe.
(http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7u40-b43/java/lang/ApplicationShutdownHooks.java#ApplicationShutdownHooks)

Example for thread-safe with addShutdownHook:

```clojure
(def threads (mapv #(Thread. (fn [] (println %))) (range 1 100)))

(doseq [t threads]
  (Thread/sleep (rand-int 100))
  (.addShutdownHook (Runtime/getRuntime) t))

(every? true? (mapv #(.removeShutdownHook (Runtime/getRuntime) %) threads)) ;;=> true
```

**Comment by weavejester** [comment]
The `add-shutdown-hook` and `remove-shutdown-hook` functions are not thread safe. A function can consist entirely of thread-safe operations, yet still not be thread-safe in aggregate.

The `add-shutdown-hook` function you have is probably okay, since `.addShutdownHook` is unlikely to raise an exception at that point. However, the `remove-shutdown-hook` may run into problems if called by multiple threads at the same time.

The code I suggest instead ensures that `.addShutdownHook` is only ever called once, and that everything else is handled atomically via `swap!`. This has the additional advantage of correctly replacing shutdown hooks with the same key.

**Comment by eunmin** [comment]
Sorry for the delayed response. Thanks for your suggestion. I completely understand. 
I've updated code and test code. Thanks! :)

**Comment by weavejester** [comment]
Looks good. Thanks.

**Comment by eunmin** [comment]
:+1:

**Comment by kajism** [comment]
Hi, I missed some shutdown log messages in production log and it seems we should call component/stop on the running system not just the created one...

**Comment by weavejester** [comment]
You're right. Can you open a new issue for it, @kajism?

**Comment by kajism** [comment]
Ok, #45 created.

**Pull request merged**
