### PR TITLE
Set the prep-tasks to same as Leiningen's default value

### PR DESCRIPTION
**Pull request by kawasima**
The lack of  `javac` target in the prep-tasks makes me confused. I added `javac` target to the prep-tasks.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch! Could you get rid of the ending period in the commit summary? Then I'll merge.

**Comment by weavejester** [comment]
Just in case you don't know, changing the PR subject won't change the commit message automatically. You need to do:

```sh
git commit --amend
```

Modify the commit message, then:

```sh
git push -f
```

**Comment by kawasima** [comment]
Oh, I see. I tried to amend the commit message.

**Comment by weavejester** [comment]
That's amended, but you left in the "the" before "Leiningen".

**Comment by weavejester** [comment]
Thanks!

**Pull request merged**
